### PR TITLE
v1.0.0

### PR DESCRIPTION
**Pull request by chadcrowell**
Craft 4 compatibility. Successfully tested generateFromUrl and generateFromHtml via test templates. No other tests performed.

### CODE REVIEW

**Comment by kennethormandy** [comment]
Amazing, thanks @chadcrowell!

I am actively working on updating the Api2Pdf SDK version, and adding some considerations for running everything as queue jobs instead, but I wasn’t necessarily planning on changing the existing API or template hooks to do that.

It could also end up being a separate major version instead. I’ll see if I can get this tagged as a beta release quickly at least, for convenience for installing.

**Comment by rickbergmans** [comment]
@kennethormandy could you please approve this request? I am using your plugin and would like to upgrade to Craft 4, but your plugin is the only one that isn't compatible yet.

**Comment by kennethormandy** [comment]
Thanks very much for this @chadcrowell! The changes from this PR are tagged as a beta release now:

```sh
composer require kennethormandy/craft-api2pdf:^1.0.0-beta.1
```

/cc @rickbergmans 

I will tag it as stable once I have the test suite running on GitHub Actions again.

**Comment by masiorama** [comment]
Any updates on tagging as stable?

**Pull request merged**
